config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions' }
  resources :users
  resources :clues do
  	resources :answers
  end

  get 'history', to: 'history#index'
  post 'answers/evaluate'
  post 'answers/get_user_score'
  post 'users/change_password'
  root 'home#index'
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand"><%= link_to "Jeopardy", root_path %></div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.name, edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
        <li><%= link_to "History", history_path(day: @history_week) %></li>
        <% if user_signed_in? and current_user.admin? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Clues", clues_path(day: Date.today) %></li>
              <li><%= link_to "Users", users_path %></li>
            </ul>
          </li>
          <!--<li><%= link_to "Admin", clues_path(day: Date.today) %></li>
          <li><%= link_to "Users", users_path %></li>-->
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jeopardy</title>
    <%= favicon_link_tag 'jeopardy.ico' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>