config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions' }
  resources :users
  resources :clues do
  	resources :answers
  end

  get 'history', to: 'history#index'
  post 'answers/evaluate'
  post 'answers/get_user_score'
  post 'users/change_password'
  root 'home#index'
end

app/models/clue.rb
class Clue < ApplicationRecord
	has_many :answers
	validates_associated :answers

	scope :of_week, -> (week_start) {where(week: week_start.beginning_of_week)}

	Default_seq = 10

	def self.prev_week_last_clue(dt)
		Clue.where("clues.week < ?", dt.beginning_of_week).order(week: :desc, seq: :desc).first
	end

	def self.last_clues(as_of=Date.today)
		if as_of.respond_to? :beginning_of_week
			as_of = as_of.beginning_of_week
		else
			as_of = Date.parse(as_of).beginning_of_week
		end
		Clue.find_by_sql(["
			SELECT c.*
		  FROM clues c
		  JOIN (
			 		SELECT week, MAX(seq) max_seq
					FROM clues
					GROUP BY week
		 		) m ON c.week = m.week AND c.seq = m.max_seq
			WHERE c.week <= :as_of_week
		 	ORDER BY c.week DESC", as_of_week: as_of])
	end

	def week=(dt)
		if dt.respond_to? :beginning_of_week
			self[:week] = dt.beginning_of_week
		else
			self[:week] = Date.parse(dt).beginning_of_week
		end
	end

	def category=(cat)
		self[:category] = cat.upcase
	end

	def text=(txt)
		self[:text] = txt.upcase
	end

	def correct_answer=(ca)
		self[:correct_answer] = ca.upcase
	end

	def value_label
		self[:final] ? "FINAL" : "$" + self[:value].to_s
	end

	def user_answer(user_id)
		answer = Answer.where("answers.clue_id = ? AND answers.user_id = ?",
			self[:id], user_id).first
		return answer
	end

	def user_current_score(user_id)
    answers = Answer.joins(:clue).
      where("clues.week = ? AND clues.seq <= ? AND answers.user_id = ?",
        self[:week], self[:seq], user_id)
    answers.sum(:score)
	end

  def user_previous_score(user_id)
    answers = Answer.joins(:clue).
      where("clues.week = ? AND clues.seq < ? AND answers.user_id = ?",
        self[:week], self[:seq], user_id)
    answers.sum(:score)
  end

  def week_scored
    pending_answers = Answer.joins(:clue)
      .where("clues.week = ? AND clues.seq < ? AND answers.status = 0", self[:week], self[:seq])
    return pending_answers.empty?
  end

	def winning_users
		users = User.joins(answers: :clue)
			.where("clues.week = ? AND clues.seq <= ?",
				self[:week], self[:seq])
			.group(:id)
		winning_score = 0
		winners = []
		users.sort_by{ |u| [-self.user_current_score(u.id), u.name] }.each do |user|
			score = self.user_current_score(user.id)
			if score > winning_score
				winning_score = score
				winners.clear
				winners.push(user.id)
			elsif score == winning_score and !winners.include?(user.id)
				winners.push(user.id)
			end
		end
		return winners
	end
end

app/controllers/clues_controller.rb
class CluesController < ApplicationController
	before_action :authenticate_user!
	before_action do
		redirect_to root_path unless current_user && current_user.admin?
	end

	def index
		@day = Date.parse(params[:day])
		@clues = Clue.of_week(@day).eager_load(answers: :user)
		@prev_week = @day.beginning_of_week - 7
		@next_week = @day.beginning_of_week + 7
	end

	def show
		@clue = Clue.find(params[:id])
	end

	def new
		@day = Date.parse(params[:day])
		lastClue = Clue.where("week = ?", @day.beginning_of_week).order(:seq).last
		defSeq = lastClue.nil? ? Clue::Default_seq : lastClue.seq += Clue::Default_seq
		defCat = lastClue.nil? ? "" : lastClue.category

		@clue = Clue.new
		@clue.seq = defSeq
		@clue.category = defCat
		@clue.week = @day.beginning_of_week
	end

	def edit
		@day = Date.parse(params[:day])
		@clue = Clue.find(params[:id])
	end

	def create
		@clue = Clue.new(clue_params)
		if @clue.save
			redirect_to clues_path(day: @clue.week)
		else
			render 'new'
		end
	end

	def update
		@clue = Clue.find(params[:id])
		if @clue.update(clue_params)
			redirect_to clues_path(day: @clue.week)
		else
			render 'edit'
		end
	end

	def destroy
		@clue = Clue.find(params[:id])
		day = @clue.week
		@clue.destroy
		redirect_to clues_path(day: day)
	end

	private

	def clue_params
		params.require(:clue).permit(:category, :text, :value, :final, :week, :seq, :correct_answer, :image)
	end
end

app/helpers/clues_helper.rb
module CluesHelper
end

app/views/clues/_clue_answers.html.erb
<% clue.answers.sort_by{ |a| [-clue.user_current_score(a.user.id), a.user.name] }.each do |answer| %>
  <tr id="<%= answer.id %>">
    <td class="answer-user" id="<%= answer.user_id %>"><%= link_to answer.user.name, answer.user %>
      <% if @last_winners.any? {|u| u.id == answer.user_id} %> <%= image_tag('thinker.gif', id: 'thinker') %> <% end %>
    </td>
    <td><div class="<%= case answer.status when 1 then 'answer-correct' when -1 then 'answer-incorrect' else 'answer-pending' end %>"><%= answer.response %></div></td>
    <% if clue.final? %>
      <td class='j-score text-right'>$<%= number_with_delimiter(answer.wager) %>/<br>$<%= number_with_delimiter(clue.user_previous_score(answer.user_id)) %>&nbsp;</td>
    <% end %>
  </tr>
<% end %>

app/views/clues/_form.html.erb
<%= form_for @clue do |f| %>
	<div class='row'>
		<div class='form_group'>
			<div class='col-md-12'>
				<% if @clue.errors.any? %>
					<div id="error_explanation">
						<h2 style='color: red'>
							<%= pluralize(@clue.errors.count, "error") %> prohibited
							this clue from being saved:
						</h2>
						<ul style='color: red'>
							<% @clue.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
				<% end %>
			</div>
		</div>
	</div>
	<div class='row'>
		<div class='form_group'>
			<div class='col-md-1'><%= f.label :category, class: 'control-label' %></div>
			<div class='col-md-11'><%= f.text_field :category, class: 'form-control' %></div>
		</div>
	</div>
	<div class='row'>
		<div class='form_group'>
			<div class='col-md-1'><%= f.label :value, class: 'control-label' %></div>
			<div class='col-md-11'><%= f.text_field :value, class: 'form-control' %></div>
		</div>
	</div>
	<div class='row'>
		<div class='form_group'>
			<div class='col-md-1'><%= f.label :text, class: 'control-label' %></div>
			<div class='col-md-11'><%= f.text_area :text, class: 'form-control' %></div>
		</div>
	</div>
	<div class='row'>
		<div class='form_group'>
			<div class='col-md-1'><%= f.label :correct_answer, class: 'control-label' %></div>
			<div class='col-md-11'><%= f.text_field :correct_answer, class: 'form-control' %></div>
		</div>
	</div>
	<div class='row'>
		<div class='form_group'>
			<div class='col-md-1'><%= f.label :final, class: 'control-label' %></div>
			<div class='col-md-11'><%= f.check_box :final, class: 'form-control' %></div>
		</div>
	</div>
	<div class='row'>
		<div class='form_group'>
			<div class='col-md-1'><%= f.label :image, class: 'control-label' %></div>
			<div class='col-md-11'><%= f.text_field :image, class: 'form-control' %></div>
		</div>
	</div>
	<div class='row'>
		<div class='form_group'>
			<div class='col-md-1'><%= f.label :week, class: 'control-label' %></div>
			<div class='col-md-11'><%= f.date_field :week, class: 'form-control' %></div>
		</div>
	</div>
	<div class='row'>
		<div class='form_group'>
			<div class='col-md-1'><%= f.label :seq, class: 'control-label' %></div>
			<div class='col-md-11'><%= f.number_field :seq, class: 'form-control' %></div>
		</div>
	</div>
	<div class='row'>
		<div class='col-md-12'>
			<div class='form_group' style='padding-top: 10px'>
				<%= f.submit 'Submit', class: 'btn btn-success' %>
			</div>
		</div>
	</div>
<% end %>

app/views/clues/_last_winners.html.erb
<table class='table table-bordered'>
  <tr>
    <th colspan="2">
      <h4>Last Week's Winner<%= @last_winners.length > 1 ? "s" : "" %></h4>
    </th>
  </tr>
  <tr>
    <th>Player</th>
    <th>Streak</th>
  </tr>
  <% if !current_user.nil? and !@last_winners.empty? %>
    <% @last_winners.each do |winner| %>
      <tr>
        <td><%= link_to winner.name, winner %> <%= image_tag('thinker.gif', id: 'thinker') %></td>
        <td class='text-right'><%= winner.winning_streak(@prev_week) %></td>
      </tr>
    <% end %>
  <% end %>
</table>
<br>

app/views/clues/_scoreboard.html.erb
<table class='table table-bordered'>
  <tr>
    <th colspan="2">
      <h4>Current Scores</h4>
    </th>
  </tr>
  <tr>
    <th>Player</th>
    <th>Score</th>
  </tr>
  <% if !current_user.nil? and !@scoreClue.nil? %>
    <% @scoreUsers.sort_by{ |u| [-@scoreClue.user_current_score(u.id), u.name] }.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %>
          <% if @last_winners.any? {|u| u.id == user.id} %> <%= image_tag('thinker.gif', id: 'thinker') %> <% end %>
        </td>
        <td class="j-score text-right">$<%= number_with_delimiter(@scoreClue.user_current_score(user.id)) %></td>
      </tr>
    <% end %>
  <% end %>
</table>
<br>

app/views/clues/_show.html.erb
<div class='container-fluid'>
	<div class='row'>
		<div class='col-md-6'>
			<table class='table table-bordered'>
				<tr><td>
					<div class='clearfix'>
						<div class='pull-left'>
							<h3 class='j-header'><%= clue.category %></h3>
						</div>
						<div class='pull-right'>
							<h3 class='j-score'><%= clue.value_label %></h3>
						</div>
					</div>
				</td></tr>
				<tr><td>
					<% if !current_user.nil? and @userCurrentClue.seq >= clue.seq and (!clue.final? or current_user.clue_wagered(clue.id)) %>
						<p class='j-clue'>
							<%= clue.text %>
						</p>
						<% if !clue.image.nil? and clue.image != '' %>
							<img class='img-responsive center-block' src="<%= clue.image %>" alt="<%= clue.image %>" />
						<% end %>
					<% end %>
				</td></tr>
				<tr><td>
					<% if !current_user.nil? and (current_user.clue_answered(clue.id) or @userCurrentClue.seq > clue.seq) %>
						<h6 class='text-center'><%= clue.correct_answer %></h6>
					<% end %>
				</td></tr>
			</table>
		</div>
		<div class='col-md-6'>
			<table class='table table-bordered'>
				<tr>
					<th class='col-player'>Player</th>
					<th>Response</th>
					<% if clue.final? %>
						<th class='col-wager'>Wager</th>
					<% end %>
				</tr>
				<% if !current_user.nil? and (current_user.clue_answered(clue.id) or @userCurrentClue.seq > clue.seq) %>
					<%= render partial: 'clues/clue_answers', locals: {clue: clue} %>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/clues/_show_admin.html.erb
<div class='container-fluid'>
	<div class='row'>
		<div class='col-md-5'>
			<table class='table table-bordered'>
				<tr><td>
					<div class='clearfix'>
						<div class='pull-left'>
							<h3 class='j-header'><%= link_to clue.category, edit_clue_path(id: clue, day: @day) %></h3>
						</div>
						<div class='pull-right'>
							<h3 class='j-score'><%= clue.value_label %></h3>
						</div>
					</div>
				</td></tr>
				<tr><td>
					<p class='j-clue'>
						<%= clue.text %>
					</p>
					<% if !clue.image.nil? and clue.image != '' %>
						<img class='img-responsive center-block' src="<%= clue.image %>" alt="<%= clue.image %>" />
					<% end %>
				</td></tr>
				<tr><td>
					<h6 class='text-center'><%= clue.correct_answer %></h6>
				</td></tr>
			</table>
		</div>
		<div class='col-md-7'>
			<table class='table table-bordered'>
				<tr>
					<th>Player</th>
					<th>Response</th>
					<th>Score</th>
					<% if clue.final? %>
						<th>Wager</th>
						<th>Final Score</th>
					<% end %>
					<th></th>
					<th></th>
					<th></th>
				</tr>
				<% clue.answers.sort_by{ |a| [-clue.user_current_score(a.user.id), a.user.name] }.each do |answer| %>
					<tr id="<%= answer.id %>">
						<td class="answer-user" id="<%= answer.user_id %>"><%= answer.user.name %></td>
						<td><div id='answer-response' class="<%= case answer.status when 1 then 'answer-correct' when -1 then 'answer-incorrect' else 'answer-pending' end %>">
							<%= answer.response %>
						</div></td>
						<% if clue.final? %>
							<td class='previous_score j-score text-right'>$<%= clue.user_previous_score(answer.user.id) %></td>
							<td class='j-score text-right'>$<%= answer.wager %></td>
							<td class='current_score j-score text-right'>$<%= clue.user_current_score(answer.user.id) %></td>
						<% else %>
							<td class='current_score j-score text-right'>$<%= clue.user_current_score(answer.user.id) %></td>
						<% end %>
						<td>
							<div class='text-center'>
								<button class="btn btn_correct" type="button" data-clue="<%= clue.id %>" data-answer="<%= answer.id %>">Correct</button>
								<br>
								<button class="btn btn_incorrect" type="button" data-clue="<%= clue.id %>" data-answer="<%= answer.id %>">Incorrect</button>
							</div>
						</td>
						<td><div class='text-center'><%= link_to "Edit", edit_clue_answer_path(clue_id: answer.clue_id, id: answer.id, day: @day), class: 'btn btn-info' %></div></td>
						<td><div class='text-center'><button class="btn btn-danger btn_delete" type="button" data-clue="<%= clue.id %>" data-answer="<%= answer.id %>">Delete</button></div></td>
						<!--<td><button class="btn btn_incorrect" type="button" data-clue="<%= clue.id %>" data-answer="<%= answer.id %>">Incorrect</button></td>
						<td><%= link_to "Edit", edit_clue_answer_path(clue_id: answer.clue_id, id: answer.id, day: @day), class: 'btn btn-info' %></td>
						<td><button class="btn btn-danger btn_delete" type="button" data-clue="<%= clue.id %>" data-answer="<%= answer.id %>">Delete</button></td> -->
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/clues/_show_history.html.erb
<div class='container-fluid'>
	<div class='row'>
		<div class='col-md-6'>
			<table class='table table-bordered'>
				<tr><td>
					<div class='clearfix'>
						<div class='pull-left'>
							<h3 class='j-header'><%= clue.category %></h3>
						</div>
						<div class='pull-right'>
							<h3 class='j-score'><%= clue.value_label %></h3>
						</div>
					</div>
				</td></tr>
				<tr><td>
					<p class='j-clue'>
						<%= clue.text %>
					</p>
					<% if !clue.image.nil? and clue.image != '' %>
						<img class='img-responsive center-block' src="<%= clue.image %>" alt="<%= clue.image %>" />
					<% end %>
				</td></tr>
				<tr><td>
					<h6 class='text-center'><%= clue.correct_answer %></h6>
				</td></tr>
			</table>
		</div>
		<div class='col-md-6'>
			<table class='table table-bordered'>
				<tr>
					<th class='col-player'>Player</th>
					<th>Response</th>
					<% if clue.final? %>
						<th class='col-wager'>Wager</th>
					<% end %>
				</tr>
				<% if !current_user.nil? %>
					<%= render partial: 'clues/clue_answers', locals: {clue: clue} %>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/clues/edit.html.erb
<div class='container'>
	<div class='row'>
		<div class='col-md-12'>
			<h3>Editing Clue...</h3>
			<h4><%= @clue.category + " " + @clue.value_label %></h4>
		</div>
	</div>
	<div class='row'>
		<div class='col-md-12'>
			<%= render 'form' %>
		</div>
	</div>
	<div class='row'>
		<div class='col-md-6' style='padding-top: 20px'>
		<%= button_to 'Delete Clue', clue_path(@clue),
			method: :delete,
			data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
		</div>
	</div>
	<div class='row'>
		<div class='col-md-6' style='padding-top: 20px'>
			<%= link_to 'Back', clues_path(day: @day), class: 'btn btn-default' %>
		</div>
	</div>
</div>

app/views/clues/index.html.erb
<div class='container'>
	<div class=-'row'>
		<div class='col-md-12' >
			<h2 class='text-center'><%= @day.beginning_of_week %></h2>
		</div>
	</div>
	<div class='row'>
		<div class='col-md-12'>
			<ul class="pager">
			  <li class="previous"><%= link_to 'Previous Week', clues_path(day: @prev_week) %></li>
				<li><%= link_to 'New Clue', new_clue_path(day: @day) %></li>
			  <li class="next"><%= link_to 'Next Week', clues_path(day: @next_week) %></li>
			</ul>
		<div>
	</div>
	<div class='row'>
		<div class='col-md-12'>
			<table class='table'>
				<% @clues.order(week: :desc, seq: :desc).each do |clue| %>
					<tr>
						<td>
							<%= render partial: 'show_admin', locals: {clue: clue} %>
						</td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/clues/new.html.erb
<div class='container'>
	<div class='row'>
		<div class='col-md-12'>
			<h3>New Clue</h3>
		</div>
	</div>
	<div class='row'>
		<div class='col-md-12'>
			<%= render 'form' %>
		</div>
	</div>
	<div class='row'>
		<div class='col-md-12' style='padding-top: 20px'>
			<%= link_to 'Back', clues_path(day: @day), class: 'btn btn-default' %>
		</div>
	</div>
</div>